# Generated by Django 5.2.7 on 2025-10-10 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='performance_indicators',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='resources_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(default='pending', max_length=64),
        ),
        migrations.AddField(
            model_name='activity',
            name='timeline',
            field=models.CharField(choices=[('one-off', 'One-off'), ('yearly', 'Yearly'), ('quarterly', 'Quarterly'), ('term', 'Term')], default='one-off', max_length=32),
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='task_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.tasktable'),
        ),
        migrations.AlterField(
            model_name='tasktable',
            name='timeline',
            field=models.CharField(choices=[('one-off', 'One-off'), ('yearly', 'Yearly'), ('quarterly', 'Quarterly'), ('term', 'Term')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tasktable',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
