# Generated by Django 5.2.7 on 2025-10-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_timelineentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Completed')], default='pending', max_length=64),
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='old_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Completed')], max_length=20),
        ),
    ]
